/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author marina
 */
public class EditMenu extends javax.swing.JFrame {

    /**
     * Creates new form EditMenu
     */
    public EditMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChoose = new javax.swing.JPanel();
        btnRoutines = new javax.swing.JButton();
        btnExercises = new javax.swing.JButton();
        lblChoose = new javax.swing.JLabel();
        pnlEditRoutines = new javax.swing.JPanel();
        lblEditRoutine = new javax.swing.JLabel();
        btnCreateRoutine = new javax.swing.JButton();
        btnChangeRoutine = new javax.swing.JButton();
        btnDeleteRoutine = new javax.swing.JButton();
        pnlEditExercises = new javax.swing.JPanel();
        lblEditExercises = new javax.swing.JLabel();
        btnCreateExercise = new javax.swing.JButton();
        btnChangeExercise = new javax.swing.JButton();
        btnDeleteExercise = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        btnRoutines.setText("Routines");
        btnRoutines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoutinesActionPerformed(evt);
            }
        });

        btnExercises.setText("Exercises");

        lblChoose.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblChoose.setText("Choose something to edit");

        javax.swing.GroupLayout pnlChooseLayout = new javax.swing.GroupLayout(pnlChoose);
        pnlChoose.setLayout(pnlChooseLayout);
        pnlChooseLayout.setHorizontalGroup(
            pnlChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChooseLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnRoutines, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExercises, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(pnlChooseLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChooseLayout.setVerticalGroup(
            pnlChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChooseLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(pnlChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoutines, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExercises, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        getContentPane().add(pnlChoose, "card2");

        lblEditRoutine.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblEditRoutine.setText("Edit Routines");

        btnCreateRoutine.setText("Create ");

        btnChangeRoutine.setText("Change");

        btnDeleteRoutine.setText("Delete");

        javax.swing.GroupLayout pnlEditRoutinesLayout = new javax.swing.GroupLayout(pnlEditRoutines);
        pnlEditRoutines.setLayout(pnlEditRoutinesLayout);
        pnlEditRoutinesLayout.setHorizontalGroup(
            pnlEditRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditRoutinesLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(pnlEditRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        pnlEditRoutinesLayout.setVerticalGroup(
            pnlEditRoutinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditRoutinesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnChangeRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnDeleteRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(pnlEditRoutines, "card3");

        lblEditExercises.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblEditExercises.setText("Edit Exercises");

        btnCreateExercise.setText("Create ");

        btnChangeExercise.setText("Change");

        btnDeleteExercise.setText("Delete");

        javax.swing.GroupLayout pnlEditExercisesLayout = new javax.swing.GroupLayout(pnlEditExercises);
        pnlEditExercises.setLayout(pnlEditExercisesLayout);
        pnlEditExercisesLayout.setHorizontalGroup(
            pnlEditExercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditExercisesLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(pnlEditExercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditExercises, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        pnlEditExercisesLayout.setVerticalGroup(
            pnlEditExercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditExercisesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditExercises, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnChangeExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnDeleteExercise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(pnlEditExercises, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoutinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoutinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRoutinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeExercise;
    private javax.swing.JButton btnChangeRoutine;
    private javax.swing.JButton btnCreateExercise;
    private javax.swing.JButton btnCreateRoutine;
    private javax.swing.JButton btnDeleteExercise;
    private javax.swing.JButton btnDeleteRoutine;
    private javax.swing.JButton btnExercises;
    private javax.swing.JButton btnRoutines;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblEditExercises;
    private javax.swing.JLabel lblEditRoutine;
    private javax.swing.JPanel pnlChoose;
    private javax.swing.JPanel pnlEditExercises;
    private javax.swing.JPanel pnlEditRoutines;
    // End of variables declaration//GEN-END:variables
}
