/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Persistence;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import model.Workout;

/**
 *
 * @author marina
 */
public class StatisticsMenu extends Menu {

	/**
	 * 
	 */
	private static final long serialVersionUID = -835080662028457249L;
	@SuppressWarnings("rawtypes")
	private JList list;

	/**
	 * Creates new form StatisticsMenu
	 * 
	 * @throws java.io.IOException
	 * @throws java.lang.ClassNotFoundException
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public StatisticsMenu() throws IOException, ClassNotFoundException {
		super();
		initComponents();
		String[] dates = { "No workout found" };
		workoutManager = Persistence.read("workoutManager.txt");
		if (workoutManager.getRegisteredDates() != null && !workoutManager.getRegisteredDates().isEmpty()) {
			dates = workoutManager.getRegisteredDates().toArray(new String[workoutManager.getRegisteredDates().size()]);
		}
		list = new JList(dates);
		list.setSelectionMode(SINGLE_SELECTION);
		workoutListPanel.add(list);
		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		workoutListPanel = new javax.swing.JScrollPane();
		btnCancel = new javax.swing.JButton();
		btnCheck = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		btnCancel.setText("Cancel");

		btnCheck.setText("Check");
		btnCheck.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCheckActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(workoutListPanel, javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGap(0, 304, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(workoutListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnCheck)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
						.addComponent(btnCancel).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckActionPerformed
		if (!list.isSelectionEmpty()) {
			Workout workout = workoutManager
					.getWorkout(workoutManager.getRegisteredDates().get(list.getSelectedIndex()));
		}
	}// GEN-LAST:event_btnCheckActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StatisticsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StatisticsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StatisticsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StatisticsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new StatisticsMenu().setVisible(true);
				} catch (IOException ex) {
					Logger.getLogger(StatisticsMenu.class.getName()).log(Level.SEVERE, null, ex);
				} catch (ClassNotFoundException ex) {
					Logger.getLogger(StatisticsMenu.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnCheck;
	private javax.swing.JScrollPane workoutListPanel;
	// End of variables declaration//GEN-END:variables
}
